// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/501urchin/portfolio/components"

type WorkCard struct {
	Slug string
	Opt  components.EntryCardOptions
}

const AboutJob = `I'm a self taught software engineer with a focus on Go, PostgreSQL,
and SolidJS. I build everything from web applications and quant
trading models to complete, production ready systems. I enjoy picking
up new technologies and am always open to working with different
stacks.`

var myWorkCards = []WorkCard{
	{
		Slug: "2025",
		Opt: components.EntryCardOptions{
			Title:       "Revala",
			Description: "Agentic marketing platform. From competitor analysis to publishing winning ads, Revala's agent does it all.",
			ProjectUrl:  "https://www.revala.io",
			Tags:        []string{"Go", "Postgres", "SolidJS", "Weaviate"},
			IconUrl:     "",
		},
	},
	{
		Slug: "2024",
		Opt: components.EntryCardOptions{
			Title:       "Stegano",
			Description: "The fastest steganography library in the Go ecosystem. Features variable-bit encoding, audio steganography, Reed–Solomon error correction, etc.",
			ProjectUrl:  "https://github.com/501urchin/stegano",
			Tags:        []string{"Go"},
			IconUrl:     "",
		},
	},
	{
		Slug: "Ongoing",
		Opt: components.EntryCardOptions{
			Title:       "Eximius",
			Description: "Search engine supporting lexical and semantic search indexed on over a million pages. Uses custom built ranking algorithm based on google's pagerank",
			ProjectUrl:  "https://github.com/501urchin/eximius",
			Tags:        []string{"Rust", "Postgres", "Ollama", "Svelte"},
			IconUrl:     "",
		},
	},
	{
		Slug: "Ongoing",
		Opt: components.EntryCardOptions{
			Title:       "Oxide",
			Description: "CLI tool to provision and deploy to remote servers using a simple config file. Supports rolling releases and rollbacks.",
			ProjectUrl:  "https://github.com/501urchin/oxide",
			Tags:        []string{"C++", "Docker"},
			IconUrl:     "",
		},
	},
}

func App() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col w-full sm:w-[60ch] gap-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ProfileCard().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextCard("About", AboutJob).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"text-text text-sm mt-5 mb-3\">My Work</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, cards := range myWorkCards {
			templ_7745c5c3_Err = components.EntryCard(cards.Slug, cards.Opt).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
