// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package src

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/501urchin/portfolio/src/components"

type WorkCard struct {
	Slug string
	Opt  components.EntryCardOptions
}

const AboutJob = `I'm a self taught software engineer with a focus on Go, PostgreSQL,
and SolidJS. I build everything from web applications and quant
trading models to complete, production ready systems. I enjoy picking
up new technologies and am always open to working with different
stacks.`

var myWorkCards = []WorkCard{
	{
		Slug: "2025",
		Opt: components.EntryCardOptions{
			Title:       "Revala",
			Description: "Agentic marketing platform. From competitor analysis to publishing winning ads, Revala's agent does it all.",
			ProjectUrl:  "https://www.revala.io",
			Tags:        []string{"Go", "Postgresql", "SolidJS"},
			IconUrl:     "",
		},
	},
	{
		Slug: "2024",
		Opt: components.EntryCardOptions{
			Title:       "Stegano",
			Description: "The fastest steganography library in the Go ecosystem. Features variable-bit encoding, audio steganography, Reed–Solomon error correction, etc.",
			ProjectUrl:  "https://github.com/501urchin/stegano",
			Tags:        []string{"Go"},
			IconUrl:     "",
		},
	},
	{
		Slug: "Ongoing",
		Opt: components.EntryCardOptions{
			Title:       "Eximius",
			Description: "Search engine supporting lexical and semantic search indexed on over a million pages. Uses custom built ranking algorithm based on google's pagerank",
			ProjectUrl:  "https://github.com/501urchin/eximius",
			Tags:        []string{"Go", "Postgresql", "Templ"},
			IconUrl:     "",
		},
	},
	{
		Slug: "Ongoing",
		Opt: components.EntryCardOptions{
			Title:       "Oxide",
			Description: "CLI tool to provision and deploy to remote servers using a simple config file. Supports rolling releases and rollbacks.",
			ProjectUrl:  "https://github.com/501urchin/oxide",
			Tags:        []string{"Rust"},
			IconUrl:     "",
		},
	},
}

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"theme-color\" content=\"#000000\"><meta name=\"description\" content=\"Jayac — Full-stack developer portfolio featuring projects, skills, and contact information.\"><meta name=\"keywords\" content=\"Jayac, portfolio, web developer, software engineer, projects, JavaScript, React, frontend, backend\"><meta name=\"author\" content=\"Jayac\"><meta name=\"robots\" content=\"index, follow\"><!-- Preload critical fonts --><link rel=\"preload\" href=\"/static/fonts/Satoshi-Variable.woff2\" as=\"font\" type=\"font/woff2\" crossorigin=\"anonymous\"><!-- Preload critical image --><link rel=\"preload\" href=\"/static/profile.png\" as=\"image\"><link rel=\"icon\" href=\"/static/profile.png\"><title>Jayac portfolio</title><link rel=\"stylesheet\" href=\"/static/tailwind.css\"></head><body class=\"font-sans bg-bg-dark flex p-2 sm:p-0 min-h-screen h-full justify-center overscroll-none flex-col items-center\"><div class=\"flex flex-col w-full sm:w-[60ch] gap-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ProfileCard().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextCard("About", AboutJob).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"text-text text-sm mt-5 mb-3\">My Work</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, cards := range myWorkCards {
			templ_7745c5c3_Err = components.EntryCard(cards.Slug, cards.Opt).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
