// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package src

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Root() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"theme-color\" content=\"#000000\"><meta name=\"description\" content=\"Jayac — Full-stack developer portfolio featuring projects, skills, and contact information.\"><meta name=\"keywords\" content=\"Jayac, portfolio, web developer, software engineer, projects, JavaScript, React, frontend, backend\"><meta name=\"author\" content=\"Jayac\"><meta name=\"robots\" content=\"index, follow\"><link rel=\"stylesheet\" href=\"/static/tailwind.css\"><meta name=\"google-site-verification\" content=\"S6SsDdP3aSLuDQD7411noqxx3WVqIMvEggAfnEeIIGY\"><link rel=\"icon\" href=\"/static/profile.png\"><!-- Preload critical fonts --><link rel=\"preload\" href=\"/static/fonts/Satoshi-Variable.woff2\" as=\"font\" type=\"font/woff2\" crossorigin=\"anonymous\"><!-- Preload critical image --><link rel=\"preload\" href=\"/static/profile.png\" as=\"image\"><title>Jayac portfolio</title></head><body class=\"font-sans bg-bg-dark flex p-2  sm:p-0 min-h-screen h-full justify-center overscroll-none flex-col items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = index().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
